# Generated by Django 4.1.7 on 2023-03-02 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("locality", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=20)),
                ("pincode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CH", "Chandigarh"),
                            ("CT", "Chhattisgarh"),
                            ("DH", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TG", "Telangana"),
                            ("TR", "Tripura"),
                            ("UT", "Uttarakhand"),
                            ("UP", "Uttar Pradesh"),
                            ("WB", "West Bengal"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=254, verbose_name="Customer Name"),
                ),
                ("amount", models.FloatField(verbose_name="Amount")),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=254, verbose_name="Payment Status"
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(max_length=40, verbose_name="Order ID"),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=36, verbose_name="Payment ID"),
                ),
                (
                    "signature_id",
                    models.CharField(max_length=128, verbose_name="Signature ID"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("phone_no", models.IntegerField(unique=True)),
                ("Address", models.TextField(max_length=200)),
                ("Pincode", models.IntegerField(null=True)),
                ("is_farmer", models.BooleanField(default=False)),
                ("is_customer", models.BooleanField(default=False)),
                ("is_deliverer", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discountd_price", models.FloatField()),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("V", "Vegitable"),
                            ("F", "Fruits"),
                            ("M", "Milk"),
                            ("Fi", "Fish"),
                        ],
                        max_length=2,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("Product_Added_date", models.DateTimeField(auto_now_add=True)),
                ("product_image", models.ImageField(upload_to="ProductImages")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderPlaced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiry", models.PositiveIntegerField(default=1)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Packed", "Packed"),
                            ("On the way", "On the way"),
                            ("Delivered", "Delevered"),
                            ("Cancle", "Cancle"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataApp.customerprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataApp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiry", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataApp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
